name: 'Modern web app preview environments'
description: 'Will create and delete resources for pull requests' preview environments'
author: 'Ecair Engineering'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'
  flyAppId:
    required: true
  flyToken: 
    required: true
  containerImgUrl: 
    required: true
  cloudflareToken: 
    required: true
  cloudflareAccountId: 
    required: true
  neonApiToken: 
    required: true
  event: 
    required: true
  refName: 
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
